Added solution to SourceTree issue from pre-commit
Added solution to SourceTree issue from pre-commit node module. NOT tested.

diff --git a/hook b/hook
--- a/hook
+++ b/hook
@@ -1,5 +1,25 @@
 #!/bin/bash
 
+HAS_NODE=`which node 2> /dev/null || which nodejs 2> /dev/null || which iojs 2> /dev/null`
+
+# TAKEN FROM pre-commit node module
+# There are some issues with Source Tree because paths are not set correctly for
+# the given environment. Sourcing the bash_profile seems to resolve this for bash users,
+# sourcing the zshrc for zshell users.
+#
+# https://answers.atlassian.com/questions/140339/sourcetree-hook-failing-because-paths-don-t-seem-to-be-set-correctly
+#
+function source_home_file {
+  file="$HOME/$1"
+  [[ -f "${file}" ]] && source "${file}"
+}
+
+if [[ -z "$HAS_NODE" ]]; then
+  source_home_file ".bash_profile" || source_home_file ".zshrc" || source_home_file ".bashrc" || true
+fi
+
+
+
 git stash -q --keep-index
 
 NODE=`which node 2> /dev/null`
